spring:
  profiles:
    active: dev # 激活开发环境配置

---
# 端口
server:
  port: 8081
# 数据源配置
spring:
  profiles: dev # 开发环境
  datasource:
    url: jdbc:oracle:thin:@192.168.1.211:1521:tansun
    username: datagovern
    password: datagovern
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: microservice-product-config #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.demo.springCloud.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

eureka:
  client:
    registerWithEureka: true # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      defaultZone:  http://activate.navicat1.com:6002/eureka/,http://activate.navicat.com:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址